//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthUpdate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double CPU { get; set; }
        public decimal RAM { get; set; }
        public double DISK { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
